const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('eAPI', {
  winMin: () => ipcRenderer.invoke('win-min'),
  winMax: () => ipcRenderer.invoke('win-max'),
  winClose: () => ipcRenderer.invoke('win-close'),
  winIsMax: () => ipcRenderer.invoke('win-is-max'),
  sessionCreate: (id, ephem) => ipcRenderer.invoke('session-create', id, ephem),
  sessionClear: (id, ephem) => ipcRenderer.invoke('session-clear', id, ephem),
  sessionApplySettings: () => ipcRenderer.invoke('session-apply-settings'),
  usersInit: () => ipcRenderer.invoke('users-init'),
  onboardingComplete: (d) => ipcRenderer.invoke('onboarding-complete', d),
  usersSwitch: (id) => ipcRenderer.invoke('users-switch', id),
  usersCreate: (d) => ipcRenderer.invoke('users-create', d),
  usersRemove: (id) => ipcRenderer.invoke('users-remove', id),
  userMainPartition: () => ipcRenderer.invoke('user-main-partition'),
  sessionSave: (d) => ipcRenderer.invoke('session-save', d),
  sessionLoad: () => ipcRenderer.invoke('session-load'),
  validateUrl: (url) => ipcRenderer.invoke('validate-url', url),
  historyLoad: () => ipcRenderer.invoke('history-load'),
  historyAdd: (e) => ipcRenderer.invoke('history-add', e),
  historyClear: () => ipcRenderer.invoke('history-clear'),
  historyDelete: (url) => ipcRenderer.invoke('history-delete', url),
  bmLoad: () => ipcRenderer.invoke('bm-load'),
  bmSave: (d) => ipcRenderer.invoke('bm-save', d),
  exportBookmarks: (d) => ipcRenderer.invoke('export-bookmarks', d),
  importBookmarks: () => ipcRenderer.invoke('import-bookmarks'),
  settingsLoad: () => ipcRenderer.invoke('settings-load'),
  settingsSave: (d) => ipcRenderer.invoke('settings-save', d),
  notesLoad: () => ipcRenderer.invoke('notes-load'),
  notesSave: (t) => ipcRenderer.invoke('notes-save', t),
  clearBrowsingData: () => ipcRenderer.invoke('clear-browsing-data'),
  blockedCount: () => ipcRenderer.invoke('blocked-count'),
  blockedReset: () => ipcRenderer.invoke('blocked-reset'),
  saveScreenshot: (bytes) => ipcRenderer.invoke('save-screenshot', bytes),
  dlList: () => ipcRenderer.invoke('dl-list'),
  openFile: (p) => ipcRenderer.invoke('open-file', p),
  openExternal: (u) => ipcRenderer.invoke('open-external', u),
  clipboard: (t) => ipcRenderer.invoke('clipboard', t),
  appVersion: () => ipcRenderer.invoke('app-version'),
  checkForUpdate: () => ipcRenderer.invoke('check-for-update'),
  chromiumVersion: () => ipcRenderer.invoke('chromium-version'),
  electronVersion: () => ipcRenderer.invoke('electron-version'),
  contextMenu: (p) => ipcRenderer.invoke('context-menu', p),
  openDevTools: () => ipcRenderer.invoke('open-devtools'),
  on: (ch, fn) => ipcRenderer.on(ch, (_, ...a) => fn(...a)),
  off: (ch, fn) => ipcRenderer.off(ch, fn),
});
